fix(facade): avoid duplicated construct names for default dashboard factories (#154)
If you have multiple facades in the same app using the default `dashboardFactory`, you'll end up with errors like:

```
[...]/node_modules/constructs/lib/construct.js:335
            throw new Error(`There is already a Construct with name '${childName}' in ${typeName}${name.length > 0 ? ' [' + name + ']' : ''}`);
            ^

Error: There is already a Construct with name 'Dashboards' in MyMonitoringFacade [MyApp-NestedTest]
[...]
```

---

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license_

(cherry picked from commit 7ab639323322af73408fd13f9f2704ed8a54f4f5)